<?php
return [

    // All fields your front end may request
    'exportable_fields' => [
        'master_claim_id'    => 'master_claim_id',
        'matched_claim_id'   => 'matched_claim_id',
        'unmatched_claim_id' => 'unmatched_claim_id',
        'claim_id',
        'claim_type',
        'client_id',
        'subclient_id',
        'order_id',
        'customer_name',
        'email',
        'phone',
        'order_address1',
        'order_address2',
        'order_city',
        'order_state',
        'order_zip',
        'order_country',
        'ship_date',
        'delivery_date',
        'payment_type',
        'paid_to',
        'mailing_address1',
        'mailing_address2',
        'mailing_city',
        'mailing_state',
        'mailing_zip',
        'mailing_country',
        'order_number',
        'tracking_number',
        'date_of_issue',
        'items_purchased',
        'claim_amount',
        'amount_to_pay_out',
        'paid_amount',
        'currency',
        'issue_type',
        'description',
        'extra_info',
        'comments',
        'electronic_notice',
        'status',
        'filed_date',
        'under_review_date',
        'wod_date',
        'completed_date',
        'approved_date',
        'paid_date',
        'pending_denial_date',
        'denied_date',
        'closed_date',
        'carrier',
        'abandoned',
        'file_ip_address',
        'source',
        'created',
        'agent',
        'agent_id',
        'admin_id',
        'purchase_amount',
        'order_date',
        'merchant_id',
        'merchant_name',
        'shipping_address1',
        'billing_address1',
        'shipping_address2',
        'shipping_city',
        'shipping_state',
        'shipping_zip',
        'shipping_country',
        'billing_address2',
        'billing_city',
        'billing_state',
        'billing_zip',
        'billing_country'

    ],

    // CSV column headings
    'export_headers' => [
        'master_claim_id'    => 'Master Claim ID',
        'matched_claim_id'   => 'Matched Claim ID',
        'unmatched_claim_id' => 'Unmatched Claim ID',
        'claim_id' => 'Claim ID',
        'claim_type' => 'Claim Type',
        'client_id' => 'Client ID',
        'subclient_id' => 'Subclient ID',
        'order_id' => 'Order ID',
        'customer_name' => 'Customer Name',
        'email' => 'Email',
        'phone' => 'Phone',
        'order_address1' => 'Order Address 1',
        'order_address2' => 'Order Address 2',
        'order_city' => 'Order City',
        'order_state' => 'Order State',
        'order_zip' => 'Order Zip',
        'order_country' => 'Order Country',
        'ship_date' => 'Ship Date',
        'delivery_date' => 'Delivery Date',
        'payment_type' => 'Payment Type',
        'paid_to' => 'Paid To',
        'mailing_address1' => 'Mailing Address 1',
        'mailing_address2' => 'Mailing Address 2',
        'mailing_city' => 'Mailing City',
        'mailing_state' => 'Mailing State',
        'mailing_zip' => 'Mailing Zip',
        'mailing_country' => 'Mailing Country',
        'order_number' => 'Order Number',
        'tracking_number' => 'Tracking Number',
        'date_of_issue' => 'Date of Issue',
        'items_purchased' => 'Items Purchased',
        'claim_amount' => 'Claim Amount',
        'amount_to_pay_out' => 'Amount To Pay Out',
        'paid_amount' => 'Paid Amount',
        'currency' => 'Currency',
        'issue_type' => 'Issue Type',
        'description' => 'Description',
        'extra_info' => 'Extra Info',
        'comments' => 'Comments',
        'electronic_notice' => 'Electronic Notice',
        'status' => 'Status',
        'filed_date' => 'Filed Date',
        'under_review_date' => 'Under Review Date',
        'wod_date' => 'Waiting On Documents Date',
        'completed_date' => 'Completed Date',
        'approved_date' => 'Approved Date',
        'paid_date' => 'Paid Date',
        'pending_denial_date' => 'Pending Denial Date',
        'denied_date' => 'Denied Date',
        'closed_date' => 'Closed Date',
        'carrier' => 'Carrier',
        'abandoned' => 'Abandoned',
        'file_ip_address' => 'File IP Address',
        'source' => 'Source',
        'created' => 'Created At',
        'agent' => 'Agent',
        'agent_id' => 'Agent ID',
        'superclient_id' => 'Superclient ID',
        'superclient' => 'Superclient',
        'client' => 'Client',
        'subclient' => 'Subclient',
        'purchase_amount' => 'Purchase Amount',
        'order_date' => 'Order Date',
        'merchant_id' => 'Merchant ID',
        'merchant_name' => 'Merchant Name',
        'shipping_address1' => 'Shipping Address 1',
        'shipping_address2' => 'Shipping Address 2',
        'shipping_city' => 'Shipping City',
        'shipping_state' => 'Shipping State',
        'shipping_zip' => 'Shipping Zip',
        'shipping_country' => 'Shipping Country',
        'billing_address1' => 'Billing Address 1',
        'billing_address2' => 'Billing Address 2',
        'billing_city' => 'Billing City',
        'billing_state' => 'Billing State',
        'billing_zip' => 'Billing Zip',
        'billing_country' => 'Billing Country',
        'order_address' => [
            'Order Address 1',
            'Order Address 2',
            'Order City',
            'Order State',
            'Order Zip',
            'Order Country'
        ],
        'mailing_address' => [
            'Paid To',
            'Mailing Address 1',
            'Mailing Address 2',
            'Mailing City',
            'Mailing State',
            'Mailing Zip',
            'Mailing Country'
        ],
        'status_dates' => [
            'Filed Date',
            'Under Review Date',
            'Waiting On Documents Date',
            'Completed Date',
            'Approved Date',
            'Paid Date',
            'Pending Denial Date',
            'Denied Date',
            'Closed Date'
        ]
    ],

];
